# Generated by Django 5.0 on 2023-12-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Company View', 'Company View'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Awaiting', 'Awaiting')], default='Applied', max_length=50, null=True),
        ),
    ]
