# Generated by Django 5.0 on 2023-12-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_saved_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_job',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
